sugarcube-2:
  macros:
    new_map:
      name: new_map
      container: true
      children: ['mapnodes']
    mapnodes:
      name: mapnodes
    place_rose:
      name: place_rose
    place_mapview:
      name: place_mapview
    update_interface:
      name: update_interface
    set_mapscripts:
      name: set_mapscripts
      container: true
      children: ['onmapattempt', 'onmapstart', 'onmapend', 'onmapabort']
    onmapattempt:
      name: onmapattempt
    onmapstart:
      name: onmapstart
    onmapend:
      name: onmapend
    onmapabort:
      name: onmapabort
    mapmove:
      name: areamapmove
    connect_map:
      name: connect_map
    disconnect_map:
      name: disconnect_map
    new_entity:
      name: new_entity
    set_entity:
      name: set_entity
    delete_entity:
      name: delete_entity
