sugarcube-2:
  macros:
    new_areamap:
      name: new_areamap
      container: true
      children: ['mapview', 'mapareas']
    place_arearose:
      name: place_arearose
    update_arearose:
      name: update_arearose
    place_areamapview:
      name: place_areamapview
    update_areamapview:
      name: update_areamapview
    set_areascripts:
      name: set_areascripts
      container: true
    areamapmove:
      name: areamapmove
