sugarcube-2:
  macros:
    regionmap:
      name: regionmap
      container: true
    regionnames:
      name: regionnames
    regionrose:
      name: regionrose
      container: true
    onattempt:
      name: onattempt
    abort:
      name: abort
    disable:
      name: disable
    onabort:
      name: onabort
    onenter:
      name: onenter
    rosedisable:
      name: rosedisable
    roseenable:
      name: roseenable
